<a href="https://colab.research.google.com/github/Aryan1334/CODESOFT-TASK-2/blob/main/CREDIT_CARD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [3]:
credit_card_data =pd.read_csv('/content/creditcard.csv')

In [4]:
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [5]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
5969,6634,-1.611463,0.190648,0.901715,1.531254,-1.535865,0.799245,1.513786,0.495829,0.200390,...,0.211223,0.007477,1.026272,0.057628,-0.024955,-0.368263,0.081684,0.140669,458.92,0.0
5970,6635,-1.420272,1.449354,1.320110,-1.894320,0.913695,0.454601,0.894179,-0.385450,2.433841,...,-0.529027,-0.368394,-0.247773,-1.189156,-0.126040,0.701487,0.277333,-0.222694,0.77,0.0
5971,6637,-1.206696,0.284728,2.152053,-2.850437,-0.437285,-0.238376,-0.333341,0.334679,2.870542,...,0.039460,0.464476,-0.457193,-0.556105,0.517579,0.008006,0.366054,0.185008,14.00,0.0
5972,6644,1.067611,0.091006,-0.153917,0.704233,0.113894,-0.826866,0.567690,-0.464181,0.957295,...,-0.476723,-1.410090,-0.037550,-0.177773,0.321810,0.114930,-0.109640,0.023205,139.90,0.0
5973,6645,-0.535272,-0.132299,2.180041,1.018303,-1.498819,0.529570,0.420147,0.045445,1.543919,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5974 entries, 0 to 5973
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    5974 non-null   int64
 1   V1      5974 non-null   float64
 2   V2      5974 non-null   float64
 3   V3      5974 non-null   float64
 4   V4      5974 non-null   float64
 5   V5      5974 non-null   float64
 6   V6      5974 non-null   float64
 7   V7      5974 non-null   float64
 8   V8      5974 non-null   float64
 9   V9      5974 non-null   float64
 10  V10     5974 non-null   float64
 11  V11     5974 non-null   float64
 12  V12     5974 non-null   float64
 13  V13     5974 non-null   float64
 14  V14     5974 non-null   float64
 15  V15     5974 non-null   float64
 16  V16     5974 non-null   float64
 17  V17     5974 non-null   float64
 18  V18     5973 non-null   float64
 19  V19     5973 non-null   float64
 20  V20     5973 non-null   float64
 21  V21     5973 non-null   float64
 22  V22     5973 non-null   float64
 23  V23     5973 non-null   float64
 24  V24     5973 non-null   float64
 25  V25     5973 non-null   float64
 26  V26     5973 non-null   float64
 27  V27     5973 non-null   float64
 28  V28     5973 non-null   float64
 29  Amount  5973 non-null   float64
 30  Class   5973 non-null   float64
dtypes: float64(30), int64(1)
memory usage: 1.4 MB

In [7]:
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [8]:
credit_card_data['Class'].value_counts()

0.0    5970
1.0       3
Name: Class, dtype: int64

In [9]:
legit=credit_card_data[credit_card_data.Class ==0]
fraud=credit_card_data[credit_card_data.Class ==1]

In [10]:
print(legit.shape)
print(fraud.shape)

(5970, 31)
(3, 31)

In [11]:
legit.Amount.describe()

count    5970.000000
mean       64.965707
std       192.429839
min         0.000000
25%         4.450000
50%        15.620000
75%        56.485000
max      7712.430000
Name: Amount, dtype: float64

In [12]:
 fraud.Amount.describe()

count      3.000000
mean     256.310000
std      264.880121
min        0.000000
25%      119.965000
50%      239.930000
75%      384.465000
max      529.000000
Name: Amount, dtype: float64

In [13]:
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,2677.40201,-0.264965,0.285625,0.844580,0.102656,0.000958,0.195420,0.018542,-0.039195,0.397472,...,0.055426,-0.043268,-0.161540,-0.036683,0.028985,0.089890,-0.040132,0.025238,0.006163,64.965707
1.0,1780.00000,-2.553039,0.184644,-0.293711,2.872264,0.005330,-0.855718,-0.549831,0.308239,-1.093098,...,0.599742,0.294921,-0.177321,0.361160,-0.020311,0.056068,-0.170050,0.015979,-0.086847,256.310000

In [14]:
legit_sample=legit.sample(n=492)

In [15]:
new_dataset =pd.concat([legit_sample,fraud],axis=0)

In [16]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
3861,3412,1.207436,-0.184375,0.039587,-0.879866,-0.432978,-0.757901,-0.052869,-0.011630,1.191430,...,0.106042,0.466047,-0.027278,0.085510,0.571255,-0.558096,0.065865,0.011739,1.00,0.0
3202,2786,-0.378095,0.649305,0.984560,-2.226382,0.384646,-0.993774,1.060441,-0.272125,0.604250,...,0.090014,0.602610,-0.348324,0.007498,0.084984,-0.836417,0.234280,-0.027292,1.00,0.0
1365,1059,1.276077,-0.480325,0.646087,-0.432326,-1.327196,-1.319226,-0.310318,-0.340562,-1.054958,...,-0.415414,-0.772980,0.159586,0.957534,0.047946,0.863421,-0.054515,0.026061,48.43,0.0
5483,5523,-1.021377,0.235197,1.052442,0.167884,1.546680,1.123325,0.704855,0.233069,0.760374,...,-0.180046,-0.453199,-0.221350,-1.765449,1.005862,-0.347416,-0.093054,-0.048393,111.21,0.0
3728,3209,-1.524870,-0.114902,1.458601,-2.261048,-0.330065,0.160296,0.399075,0.342973,-1.276294,...,-0.499739,-1.010123,-0.178211,-0.286407,0.285788,0.660595,-0.439290,-0.294379,95.93,0.0

In [17]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
1927,1487,1.237891,0.227158,0.641062,0.701950,-0.680762,-1.191387,0.036879,-0.200164,0.092734,...,-0.241568,-0.721826,0.182887,0.693725,0.158356,0.075929,-0.031557,0.021254,1.29,0.0
5397,5351,-2.905390,1.445037,0.457825,0.080003,-0.361364,-0.363474,-0.432973,0.817428,1.189142,...,-0.294964,-0.654344,0.074364,-0.067224,-0.376682,-0.011763,-0.347973,0.238472,14.37,0.0
541,406,-2.312227,1.951992,-1.609851,3.997906,-0.522188,-1.426545,-2.537387,1.391657,-2.770089,...,0.517232,-0.035049,-0.465211,0.320198,0.044519,0.177840,0.261145,-0.143276,0.00,1.0
623,472,-3.043541,-3.157307,1.088463,2.288644,1.359805,-1.064823,0.325574,-0.067794,-0.270953,...,0.661696,0.435477,1.375966,-0.293803,0.279798,-0.145362,-0.252773,0.035764,529.00,1.0
4920,4462,-2.303350,1.759247,-0.359745,2.330243,-0.821628,-0.075788,0.562320,-0.399147,-0.238253,...,-0.294166,-0.932391,0.172726,-0.087330,-0.156114,-0.542628,0.039566,-0.153029,239.93,1.0

In [18]:
new_dataset['Class'].value_counts()

0.0    492
1.0      3
Name: Class, dtype: int64

In [19]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,2686.083333,-0.267165,0.293342,0.857216,0.042242,0.017348,0.089014,-0.000304,-0.046588,0.411916,...,0.028175,-0.045259,-0.124807,-0.068643,0.004503,0.107547,-0.046769,0.041471,0.026580,56.538618
1.0,1780.000000,-2.553039,0.184644,-0.293711,2.872264,0.005330,-0.855718,-0.549831,0.308239,-1.093098,...,0.599742,0.294921,-0.177321,0.361160,-0.020311,0.056068,-0.170050,0.015979,-0.086847,256.310000

In [20]:
X=new_dataset.drop(columns='Class',axis=1)
Y=new_dataset['Class']

In [21]:
print(X)

      Time        V1        V2        V3        V4        V5        V6  \
3861  3412  1.207436 -0.184375  0.039587 -0.879866 -0.432978 -0.757901
3202  2786 -0.378095  0.649305  0.984560 -2.226382  0.384646 -0.993774
1365  1059  1.276077 -0.480325  0.646087 -0.432326 -1.327196 -1.319226
5483  5523 -1.021377  0.235197  1.052442  0.167884  1.546680  1.123325
3728  3209 -1.524870 -0.114902  1.458601 -2.261048 -0.330065  0.160296
...    ...       ...       ...       ...       ...       ...       ...
1927  1487  1.237891  0.227158  0.641062  0.701950 -0.680762 -1.191387
5397  5351 -2.905390  1.445037  0.457825  0.080003 -0.361364 -0.363474
541    406 -2.312227  1.951992 -1.609851  3.997906 -0.522188 -1.426545
623    472 -3.043541 -3.157307  1.088463  2.288644  1.359805 -1.064823
4920  4462 -2.303350  1.759247 -0.359745  2.330243 -0.821628 -0.075788

            V7        V8        V9  ...       V20       V21       V22  \
3861 -0.052869 -0.011630  1.191430  ... -0.276626  0.106042  0.466047
3202  1.060441 -0.272125  0.604250  ...  0.048448  0.090014  0.602610
1365 -0.310318 -0.340562 -1.054958  ... -0.335301 -0.415414 -0.772980
5483  0.704855  0.233069  0.760374  ...  0.203948 -0.180046 -0.453199
3728  0.399075  0.342973 -1.276294  ... -0.598989 -0.499739 -1.010123
...        ...       ...       ...  ...       ...       ...       ...
1927  0.036879 -0.200164  0.092734  ... -0.134524 -0.241568 -0.721826
5397 -0.432973  0.817428  1.189142  ... -0.358854 -0.294964 -0.654344
541  -2.537387  1.391657 -2.770089  ...  0.126911  0.517232 -0.035049
623   0.325574 -0.067794 -0.270953  ...  2.102339  0.661696  0.435477
4920  0.562320 -0.399147 -0.238253  ... -0.430022 -0.294166 -0.932391

           V23       V24       V25       V26       V27       V28  Amount
3861 -0.027278  0.085510  0.571255 -0.558096  0.065865  0.011739    1.00
3202 -0.348324  0.007498  0.084984 -0.836417  0.234280 -0.027292    1.00
1365  0.159586  0.957534  0.047946  0.863421 -0.054515  0.026061   48.43
5483 -0.221350 -1.765449  1.005862 -0.347416 -0.093054 -0.048393  111.21
3728 -0.178211 -0.286407  0.285788  0.660595 -0.439290 -0.294379   95.93
...        ...       ...       ...       ...       ...       ...     ...
1927  0.182887  0.693725  0.158356  0.075929 -0.031557  0.021254    1.29
5397  0.074364 -0.067224 -0.376682 -0.011763 -0.347973  0.238472   14.37
541  -0.465211  0.320198  0.044519  0.177840  0.261145 -0.143276    0.00
623   1.375966 -0.293803  0.279798 -0.145362 -0.252773  0.035764  529.00
4920  0.172726 -0.087330 -0.156114 -0.542628  0.039566 -0.153029  239.93

[495 rows x 30 columns]

In [22]:
print(Y)

3861    0.0
3202    0.0
1365    0.0
5483    0.0
3728    0.0
       ...
1927    0.0
5397    0.0
541     1.0
623     1.0
4920    1.0
Name: Class, Length: 495, dtype: float64

In [23]:
X_train, X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)

In [24]:
print(X_train.shape,X_test.shape)

(396, 30) (99, 30)

In [25]:
model =LogisticRegression()

In [26]:
model.fit(X_train,Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [27]:
X_train_prediction=model.predict(X_train)
training_data_accuracy=accuracy_score(X_train_prediction,Y_train)

In [28]:
print('Accuracy on Training data:',training_data_accuracy)

Accuracy on Training data: 1.0

In [29]:
X_test_prediction =model.predict(X_test)
test_data_accuracy= accuracy_score(X_test_prediction,Y_test)

In [30]:
print('Accuracy score on Test on Test Data:', test_data_accuracy)

Accuracy score on Test on Test Data: 0.9797979797979798